// ======================================================== SYSTEM INIT
export const FETCH_CRISIS_TYPE_REQUESTED = "FETCH_CRISIS_TYPE_REQUESTED";
export const FETCH_CRISIS_TYPE_SUCCESS = "FETCH_CRISIS_TYPE_SUCCESS";
export const FETCH_CRISIS_TYPE_FAILURE = "FETCH_CRISIS_TYPE_FAILURE";
export const FETCH_ASSISTANCE_TYPE_REQUESTED =
  "FETCH_ASSISTANCE_TYPE_REQUESTED";
export const FETCH_ASSISTANCE_TYPE_SUCCESS = "FETCH_ASSISTANCE_TYPE_SUCCESS";
export const FETCH_ASSISTANCE_TYPE_FAILURE = "FETCH_ASSISTANCE_TYPE_FAILURE";
export const FETCH_EMERGENCY_AGENCIES_REQUESTED =
  "FETCH_EMERGENCY_AGENCIES_REQUESTED";
export const FETCH_EMERGENCY_AGENCIES_SUCCESS =
  "FETCH_EMERGENCY_AGENCIES_SUCCESS";
export const FETCH_EMERGENCY_AGENCIES_FAILURE =
  "FETCH_EMERGENCY_AGENCIES_FAILURE";

// ======================================================== COMMON USER
export const FETCH_CRISIS_REQUESTED = "FETCH_CRISIS_REQUESTED";
export const FETCH_CRISIS_SUCCESS = "FETCH_CRISIS_SUCCESS";
export const FETCH_CRISIS_FAILURE = "FETCH_CRISIS_FAILURE";
export const REPORT_CRISIS_REQUESTED = "REPORT_CRISIS_REQUESTED";
export const REPORT_CRISIS_SUCCESS = "REPORT_CRISIS_SUCCESS";
export const REPORT_CRISIS_FAILURE = "REPORT_CRISIS_FAILURE";
export const FETCH_PSI_REQUESTED = "FETCH_PSI_REQUESTED";
export const FETCH_PSI_SUCCESS = "FETCH_PSI_SUCCESS";
export const FETCH_PSI_FAILURE = "FETCH_PSI_FAILURE";
export const FETCH_HUMIDITY_REQUESTED = "FETCH_HUMIDITY_REQUESTED";
export const FETCH_HUMIDITY_SUCCESS = "FETCH_HUMIDITY_SUCCESS";
export const FETCH_HUMIDITY_FAILURE = "FETCH_HUMIDITY_FAILURE";
export const FETCH_RAINFALL_REQUESTED = "FETCH_RAINFALL_REQUESTED";
export const FETCH_RAINFALL_SUCCESS = "FETCH_RAINFALL_SUCCESS";
export const FETCH_RAINFALL_FAILURE = "FETCH_RAINFALL_FAILURE";
export const FETCH_TEMPERATURE_REQUESTED = "FETCH_TEMPERATURE_REQUESTED";
export const FETCH_TEMPERATURE_SUCCESS = "FETCH_TEMPERATURE_SUCCESS";
export const FETCH_TEMPERATURE_FAILURE = "FETCH_TEMPERATURE_FAILURE";

// ======================================================== STAFF
export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";
export const FETCH_CURRENT_USER_REQUESTED = "FETCH_CURRENT_USER_REQUESTED";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAILURE = "FETCH_CURRENT_USER_FAILURE";
export const FETCH_USER_LIST_REQUESTED = "FETCH_USER_LIST_REQUESTED";
export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS";
export const FETCH_USER_LIST_FAILURE = "FETCH_USER_LIST_FAILURE";
export const RESOLVE_CRISIS_REQUESTED = "RESOLVE_CRISIS_REQUESTED";
export const RESOLVE_CRISIS_SUCCESS = "RESOLVE_CRISIS_SUCCESS";
export const RESOLVE_CRISIS_FAILURE = "RESOLVE_CRISIS_FAILURE";
export const ADD_USER_REQUESTED = "ADD_USER_REQUESTED";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const EDIT_USER_REQUESTED = "EDIT_USER_REQUESTED";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";
export const ADD_CRISIS_TYPE_REQUESTED = "ADD_CRISIS_TYPE_REQUESTED";
export const ADD_CRISIS_TYPE_SUCCESS = "ADD_CRISIS_TYPE_SUCCESS";
export const ADD_CRISIS_TYPE_FAILURE = "ADD_CRISIS_TYPE_FAILURE";
export const ADD_ASSISTANCE_TYPE_REQUESTED = "ADD_ASSISTANCE_TYPE_REQUESTED";
export const ADD_ASSISTANCE_TYPE_SUCCESS = "ADD_ASSISTANCE_TYPE_SUCCESS";
export const ADD_ASSISTANCE_TYPE_FAILURE = "ADD_ASSISTANCE_TYPE_FAILURE";
export const ADD_EMERGENCY_AGENCIES_REQUESTED =
  "ADD_EMERGENCY_AGENCIES_REQUESTED";
export const ADD_EMERGENCY_AGENCIES_SUCCESS = "ADD_EMERGENCY_AGENCIES_SUCCESS";
export const ADD_EMERGENCY_AGENCIES_FAILURE = "ADD_EMERGENCY_AGENCIES_FAILURE";
export const EDIT_EMERGENCY_AGENCIES_REQUESTED =
  "EDIT_EMERGENCY_AGENCIES_REQUESTED";
export const EDIT_EMERGENCY_AGENCIES_SUCCESS =
  "EDIT_EMERGENCY_AGENCIES_SUCCESS";
export const EDIT_EMERGENCY_AGENCIES_FAILURE =
  "EDIT_EMERGENCY_AGENCIES_TYPE_FAILURE";
export const EDIT_SITE_SETTINGS_REQUESTED = "EDIT_SITE_SETTINGS_REQUESTED";
export const EDIT_SITE_SETTINGS_SUCCESS = "EDIT_SITE_SETTINGS_SUCCESS";
export const EDIT_SITE_SETTINGS_FAILURE = "EDIT_SITE_SETTINGS_TYPE_FAILURE";
export const DISPATCH_CRISIS_REQUESTED = "DISPATCH_CRISIS_REQUESTED";
export const DISPATCH_CRISIS_SUCCESS = "DISPATCH_CRISIS_SUCCESS";
export const DISPATCH_CRISIS_FAILURE = "DISPATCH_CRISIS_TYPE_FAILURE";

// ======================================================== MODAL
export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_HIDE = "MODAL_HIDE";
